# Generated by Django 3.1.8 on 2021-07-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('fixed', models.CharField(max_length=50)),
                ('spayed', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=50)),
                ('pets', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('pictures', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastSeen', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pictures', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstoneapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=500)),
                ('condition', models.CharField(max_length=500)),
                ('animal', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('pictures', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstoneapp.user')),
            ],
        ),
    ]
