# Generated by Django 3.1.8 on 2021-07-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petlisting',
            name='spayed',
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lastSeen',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lost',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='children',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='fixed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='pets',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstoneapp.user'),
        ),
    ]
