# Generated by Django 3.1.8 on 2021-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0005_auto_20210704_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='animal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='brand',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='condition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lastSeen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='fixed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='pets',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
